### ISSUE TITLE
Unable to import FloatingActionButton class and Snackbar class

### ISSUE THREAD

**Issue by PrafullaKumarSahu** [sanjibparida/studyjam2016example1#1]
I have posted my ManinActivity.java and build.gradle file code. My Android Studio  showing me error unable to resolve symbol FloatingActionButton and Snackbar .

MainActivity.java

```
package com.android.example.list3dview;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;

import android.app.ListActivity;
import android.support.design.widget.FloatingActionButton;
import android.support.design.widget.Snackbar;
import android.support.v7.widget.Toolbar;
import android.view.View;
import android.view.Menu;
import android.view.MenuItem;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
    }
}
```

build.gradle

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.5.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```

**Comment by somshubham** [comment]
so  you have to go to  the activity_main.xml file and remove the  code...

<android.support.design.widget.FloatingActionButton android:id="@+id/fab"
    android:layout_width="wrap_content" android:layout_height="wrap_content"
    android:layout_gravity="bottom|end" android:layout_margin="@dimen/fab_margin"
    android:src="@android:drawable/ic_dialog_email" />

and try again . 
 happy coding 
With Regards, 
Mr. Som Shubham Sahoo

**Comment by PrafullaKumarSahu** [comment]
@somshubham  thank you for your reply but my activity_main.xml file does not contains 

```
android:src="@android:drawable/ic_dialog_email"
```

and I have asked for problem in importing two classes, this does will not solve the problem, even I will create only a new project with blank activity and try to import this two classes, I am getting the same error.

I have also added support for  library using http://developer.android.com/tools/support-library/setup.html#choosing and added 

```
 compile "com.android.support:support-v4:18.0.+"
```

to my build.gradle file but still getting same error.

**Comment by somshubham** [comment]
so just try to remove the

import

import android.support.design.widget.FloatingActionButton;
import android.support.design.widget.Snackbar;

thanks
With Regards,

Mr. Som Shubham Sahoo
Regd No.: 130301CSR010
Branch CSE, CIT,3rd year
Jatni, Bhubaneswar
Mob: +91-9439539561
E-mail: 130301CSR010@cutm.ac.in

**Comment by PrafullaKumarSahu** [comment]
Why I will remove those two lines, I need those two classes for my app ?

**Comment by sanjibparida** [comment]
Add appcompat to your build gradle in dependencies like this 
compile 'com.android.support:appcompat-v7:23.1.0'

it will fix it

**Comment by PrafullaKumarSahu** [comment]
Sir, I am getting Gradle DSL method not find "compile()" error for that .

**Comment by PrafullaKumarSahu** [comment]
or may be I am missing gradle plugin missing but the list that displays plugins not showing gradle plugin .

**Comment by PrafullaKumarSahu** [comment]
@somshubham  thank you for your willingness to help .

**Comment by sanjibparida** [comment]
Seems like you may have modified the gradle file, regenerate a applicaiton that will generate a new gradle file and may solve it.

**Comment by PrafullaKumarSahu** [comment]
I have tried making a new app, that too shows same error.

**Comment by AskSnehasish** [comment]
Remove These codes from activity_main.xml:

&lt;android.support.design.widget.FloatingActionButton
    android:id="@+id/fab"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_gravity="bottom|end"
    android:layout_margin="@dimen/fab_margin"
    android:src="@android:drawable/ic_dialog_email" /&gt;

then remove these codes from MainActivity.java
FloatingActionButton fab = (FloatingActionButton) findViewById(R.id.fab);
fab.setOnClickListener(new View.OnClickListener() {
    @Override
    public void onClick(View view) {
        Snackbar.make(view, "Replace with your own action", Snackbar.LENGTH_LONG)
                .setAction("Action", null).show();
    }
});

Note:
And the build.Gradle file you have shown is for the Whole Project. You need to import support libraries into the build.gradle file of the "app" not the project. Hope it solves ur issue. 

And for Future Questions, post them on gdgbbsr.com/questions/

**Comment by PrafullaKumarSahu** [comment]
I want to use FloatingActionButton class and the button, is there any way ? I have successfully developed an app which shows list and on click it shows the selected item on a popup, removing this is some how going back . I want to add new things to it.

Re : About importing support libraries , I have already mentioned I have imported it successfully .Following   (http://developer.android.com/tools/support-library/setup.html#samples)

**Comment by AskSnehasish** [comment]
can you show me your build.gradle(Module:app) file please?

**Comment by PrafullaKumarSahu** [comment]
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"

    defaultConfig {
        applicationId "com.android.serverwarrior.list3dview"
        minSdkVersion 21
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.1.1'
}

```

**Comment by AskSnehasish** [comment]
Add this: compile 'com.android.support:design:23.1.1' to dependencies

Hope it solves your issues.

**Comment by AskSnehasish** [comment]
Please let me know if it solves your issue or not :)

**Comment by PrafullaKumarSahu** [comment]
It is too slow , but I can say my problem is solved as the classes are imported correctly .It seems there is some run time error , I will solve it . thank you .

**Comment by AskSnehasish** [comment]
Can you add this question to http://gdgbbsr.com/questions/ so that we can help other students who are having same issue?

**Comment by PrafullaKumarSahu** [comment]
ok, I will add t there,

**Comment by somshubham** [comment]
![snapshoot](https://cloud.githubusercontent.com/assets/12602212/13085006/1bf1c76c-d502-11e5-944b-5b6f45fc3e00.png)

**Comment by somshubham** [comment]
Is  this  what  you want to do ?

**Comment by AskSnehasish** [comment]
somsubham. his issue has been resolved. :)
